type VercelFile = {
  file: string;
  data: string;
  encoding?: "utf-8" | "base64";
};

type BundleInput = {
  productionPageTsx: string;
};

function sanitizeProductionPageTsx(source: string) {
  // Ensure the deployed app is a single-page landing.
  // We accept whatever the model outputs, but enforce default export if missing.
  if (/export\s+default\s+function\s+Page\s*\(/.test(source)) return source;
  if (/export\s+default\s+function\s+(\w+)\s*\(/.test(source)) return source;
  if (/export\s+default\s+/.test(source)) return source;
  return `export default function Page() {\n  return (\n    <div className="min-h-screen bg-black text-white p-8">Missing <code>export default function Page()</code></div>\n  );\n}\n`;
}

const PACKAGE_JSON = {
  name: "landing-page",
  private: true,
  version: "0.0.0",
  scripts: {
    dev: "next dev",
    build: "next build",
    start: "next start",
  },
  dependencies: {
    next: "16.1.6",
    react: "19.2.3",
    "react-dom": "19.2.3",
    "framer-motion": "^12.35.2",
    "@vercel/analytics": "^1.5.0",
    "@vercel/speed-insights": "^1.2.0",
    firebase: "^12.10.0",
    clsx: "^2.1.1",
    "tailwind-merge": "^3.5.0",
  },
  devDependencies: {
    tailwindcss: "^4",
    "@tailwindcss/postcss": "^4",
    typescript: "^5",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
  },
};

const NEXT_CONFIG_TS = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`;

const POSTCSS_CONFIG_MJS = `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`;

const TSCONFIG_JSON = {
  compilerOptions: {
    target: "ES2017",
    lib: ["dom", "dom.iterable", "esnext"],
    allowJs: true,
    skipLibCheck: true,
    strict: true,
    noEmit: true,
    esModuleInterop: true,
    module: "esnext",
    moduleResolution: "bundler",
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: "react-jsx",
    incremental: true,
    plugins: [{ name: "next" }],
    paths: { "@/*": ["./*"] },
  },
  include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  exclude: ["node_modules"],
};

const NEXT_ENV_D_TS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
`;

const GLOBALS_CSS = `@import "tailwindcss";

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;

    --card: 0 0% 100%;
    --card-foreground: 240 10% 3.9%;

    --border: 240 5.9% 90%;
    --ring: 240 5.9% 10%;
    --radius: 14px;
  }

  .dark {
    --background: 240 10% 3.9%;
    --foreground: 0 0% 98%;
    --card: 240 10% 3.9%;
    --card-foreground: 0 0% 98%;
    --border: 240 3.7% 15.9%;
    --ring: 240 4.9% 83.9%;
  }

  * {
    border-color: hsl(var(--border));
  }

  body {
    background: hsl(var(--background));
    color: hsl(var(--foreground));
  }
}
`;

const ROOT_LAYOUT_TSX = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Generated Landing Page",
  description: "Generated by Prompt-to-Production",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={\`\${geistSans.variable} \${geistMono.variable} min-h-screen bg-[hsl(var(--background))] text-[hsl(var(--foreground))] antialiased\`}>
        {children}
        {/* Vercel Web Analytics + Speed Insights (safe defaults) */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
`;

const LIB_UTILS_TS = `import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;

const VERCEL_JSON = JSON.stringify(
  {
    cleanUrls: true,
    trailingSlash: false,
    headers: [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), payment=()",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
        ],
      },
      {
        source: "/fonts/(.*)",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/images/(.*)",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
    ],
  },
  null,
  2,
);

const FIREBASE_CLIENT_TS = `import { initializeApp, getApps, type FirebaseApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

function getConfig() {
  return {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };
}

export function isFirebaseConfigured() {
  const c = getConfig();
  return Boolean(c.apiKey && c.authDomain && c.projectId && c.appId);
}

export function getFirebaseApp(): FirebaseApp | null {
  if (!isFirebaseConfigured()) return null;
  if (getApps().length) return getApps()[0]!;
  return initializeApp(getConfig());
}

export function getDb() {
  const app = getFirebaseApp();
  return app ? getFirestore(app) : null;
}
`;

const FIREBASE_LEADS_TS = `import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { getDb } from "@/lib/firebase/client";

export type LeadInput = {
  name: string;
  email: string;
  company?: string;
  message?: string;
};

export async function createLead(input: LeadInput, clientId?: string) {
  const db = getDb();
  if (!db) throw new Error("Firebase not configured");

  const resolvedClientId = (clientId || "default").trim() || "default";

  const docRef = await addDoc(collection(db, "leads", resolvedClientId, "entries"), {
    ...input,
    clientId: resolvedClientId,
    createdAt: serverTimestamp(),
    userAgent: typeof navigator !== "undefined" ? navigator.userAgent : null,
    referrer: typeof document !== "undefined" ? document.referrer : null,
    url: typeof location !== "undefined" ? location.href : null,
  });

  return { id: docRef.id };
}
`;

const CONTACT_FORM_TSX = `"use client";

import * as React from "react";
import { createLead } from "@/lib/firebase/leads";
import { GlowCard } from "@/components/magic/glow-card";
import { ShimmerButton } from "@/components/magic/shimmer-button";
import { ScrollReveal } from "@/components/magic/scroll-reveal";

type Props = {
  clientId?: string;
};

export function ContactForm({ clientId }: Props) {
  const [status, setStatus] = React.useState<"idle" | "sending" | "sent" | "error">("idle");
  const [error, setError] = React.useState<string | null>(null);

  const resolvedClientId =
    (clientId || process.env.NEXT_PUBLIC_LEADS_CLIENT_ID || "default").trim() ||
    "default";

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    setStatus("sending");

    const fd = new FormData(e.currentTarget);
    const payload = {
      name: String(fd.get("name") || "").trim(),
      email: String(fd.get("email") || "").trim(),
      company: String(fd.get("company") || "").trim() || undefined,
      message: String(fd.get("message") || "").trim() || undefined,
    };

    if (!payload.name || !payload.email) {
      setError("Please provide a name and email.");
      setStatus("error");
      return;
    }

    try {
      await createLead(payload, resolvedClientId);
      setStatus("sent");
      (e.currentTarget as HTMLFormElement).reset();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to submit.");
      setStatus("error");
    }
  }

  return (
    <ScrollReveal as="section" className="mx-auto w-full max-w-6xl px-6 pb-24">
      <div className="mb-8">
        <div className="text-sm font-semibold tracking-tight">Contact</div>
        <div className="mt-2 text-balance text-3xl font-semibold tracking-tight md:text-4xl">
          Turn interest into qualified leads.
        </div>
        <p className="mt-3 max-w-2xl text-sm leading-6 text-[hsl(var(--foreground))/0.65]">
          This form stores submissions directly in Firestore: \`leads/\${resolvedClientId}/entries\`.
        </p>
      </div>

      <GlowCard className="p-6">
        <form onSubmit={onSubmit} className="grid gap-4 md:grid-cols-2">
          <label className="grid gap-2 text-sm">
            <span className="font-medium">Name</span>
            <input
              name="name"
              required
              className="h-11 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))]/60 px-3 outline-none ring-offset-2 focus:ring-2 focus:ring-[hsl(var(--ring))]"
              placeholder="Alex Johnson"
            />
          </label>
          <label className="grid gap-2 text-sm">
            <span className="font-medium">Email</span>
            <input
              name="email"
              type="email"
              required
              className="h-11 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))]/60 px-3 outline-none ring-offset-2 focus:ring-2 focus:ring-[hsl(var(--ring))]"
              placeholder="alex@company.com"
            />
          </label>

          <label className="grid gap-2 text-sm md:col-span-2">
            <span className="font-medium">Company</span>
            <input
              name="company"
              className="h-11 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))]/60 px-3 outline-none ring-offset-2 focus:ring-2 focus:ring-[hsl(var(--ring))]"
              placeholder="Company Inc."
            />
          </label>

          <label className="grid gap-2 text-sm md:col-span-2">
            <span className="font-medium">Message</span>
            <textarea
              name="message"
              className="min-h-28 resize-none rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))]/60 px-3 py-2 outline-none ring-offset-2 focus:ring-2 focus:ring-[hsl(var(--ring))]"
              placeholder="Tell us what you’re building…"
            />
          </label>

          <div className="flex items-center justify-between gap-3 md:col-span-2">
            <div className="text-xs text-[hsl(var(--foreground))/0.65]">
              {status === "sent" ? "Thanks, we’ll reach out shortly." : null}
              {status === "sending" ? "Sending…" : null}
              {status === "error" && error ? error : null}
            </div>
            <ShimmerButton type="submit" disabled={status === "sending"} className="disabled:opacity-60">
              Request a callback
            </ShimmerButton>
          </div>
        </form>
      </GlowCard>
    </ScrollReveal>
  );
}
`;

// Keep these primitives in sync with the generator app.
const MAGIC_COMPONENTS: Record<string, string> = {
  "components/magic/animated-grid-background.tsx": `import * as React from "react";
import { cn } from "@/lib/utils";

type Props = { className?: string };

export function AnimatedGridBackground({ className }: Props) {
  return (
    <div aria-hidden="true" className={cn("pointer-events-none absolute inset-0 -z-10 overflow-hidden", className)}>
      <div className="absolute inset-0 opacity-35 [background-image:linear-gradient(to_right,hsl(var(--foreground)/0.08)_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--foreground)/0.08)_1px,transparent_1px)] [background-size:64px_64px]" />
      <div className="absolute left-1/2 top-[-30%] h-[52rem] w-[52rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle_at_center,hsl(var(--foreground)/0.14),transparent_55%)] blur-3xl" />
      <div className="absolute inset-0 [mask-image:radial-gradient(600px_circle_at_50%_20%,black,transparent_65%)]">
        <div className="absolute inset-0 animate-[pulse_6s_ease-in-out_infinite] bg-[radial-gradient(400px_circle_at_30%_20%,hsl(var(--foreground)/0.14),transparent_60%),radial-gradient(480px_circle_at_70%_0%,hsl(var(--foreground)/0.10),transparent_60%)]" />
      </div>
    </div>
  );
}
`,
  "components/magic/glow-card.tsx": `import * as React from "react";
import { cn } from "@/lib/utils";

type Props = React.HTMLAttributes<HTMLDivElement> & { glowClassName?: string };

export function GlowCard({ className, glowClassName, children, ...props }: Props) {
  return (
    <div {...props} className={cn("relative overflow-hidden rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]/60 shadow-sm backdrop-blur", className)}>
      <div className={cn("pointer-events-none absolute inset-0 opacity-70 [mask-image:radial-gradient(420px_circle_at_30%_0%,black,transparent_60%)]", glowClassName)}>
        <div className="absolute inset-0 bg-[radial-gradient(650px_circle_at_20%_0%,hsl(var(--foreground)/0.18),transparent_60%),radial-gradient(700px_circle_at_85%_40%,hsl(var(--foreground)/0.12),transparent_62%)]" />
      </div>
      <div className="relative">{children}</div>
    </div>
  );
}
`,
  "components/magic/shimmer-button.tsx": `import * as React from "react";
import { cn } from "@/lib/utils";

type Props = React.ButtonHTMLAttributes<HTMLButtonElement> & { glow?: boolean };

export function ShimmerButton({ className, glow = true, ...props }: Props) {
  return (
    <button
      {...props}
      className={cn(
        "group relative inline-flex h-11 items-center justify-center overflow-hidden rounded-xl bg-white px-6 text-sm font-semibold text-black shadow-sm transition-[transform,box-shadow] active:translate-y-px",
        glow && "hover:shadow-[0_16px_40px_rgba(255,255,255,0.16)]",
        className
      )}
    >
      <span className="pointer-events-none absolute inset-0 -z-10 opacity-60">
        <span className="absolute -left-1/3 top-0 h-full w-1/2 -skew-x-12 bg-[linear-gradient(90deg,transparent,rgba(255,255,255,0.35),transparent)] blur-sm transition-transform duration-700 group-hover:translate-x-[220%]" />
      </span>
      <span className="pointer-events-none absolute inset-0 -z-20 bg-[radial-gradient(circle_at_20%_0%,rgba(255,255,255,0.22),transparent_55%),radial-gradient(circle_at_80%_100%,rgba(255,255,255,0.14),transparent_60%)]" />
      {props.children}
    </button>
  );
}
`,
  "components/magic/spotlight.tsx": `import * as React from "react";
import { cn } from "@/lib/utils";

type Props = React.HTMLAttributes<HTMLDivElement> & { from?: string; to?: string };

export function Spotlight({ className, from = "hsl(var(--foreground)/0.14)", to = "transparent", ...props }: Props) {
  return (
    <div aria-hidden="true" className={cn("pointer-events-none absolute inset-0 -z-10", className)} {...props}>
      <div
        className="absolute left-1/2 top-[-35%] h-[58rem] w-[58rem] -translate-x-1/2 rounded-full blur-3xl"
        style={{ background: \`radial-gradient(circle at center, \${from}, \${to} 60%)\` }}
      />
      <div className="absolute inset-0 [mask-image:radial-gradient(600px_circle_at_50%_18%,black,transparent_70%)]">
        <div className="absolute inset-0 animate-[pulse_7s_ease-in-out_infinite] bg-[radial-gradient(400px_circle_at_30%_20%,hsl(var(--foreground)/0.16),transparent_60%),radial-gradient(520px_circle_at_75%_0%,hsl(var(--foreground)/0.10),transparent_60%)]" />
      </div>
    </div>
  );
}
`,
  "components/magic/bento-grid.tsx": `import * as React from "react";
import { cn } from "@/lib/utils";
import { GlowCard } from "@/components/magic/glow-card";

export function BentoGrid({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("grid gap-4 md:grid-cols-12 md:gap-5 [&>*]:min-h-[180px]", className)} {...props} />;
}

type BentoCardProps = React.HTMLAttributes<HTMLDivElement> & {
  title: string;
  description?: string;
  icon?: React.ReactNode;
  colSpan?: string;
  rowSpan?: string;
  variant?: "glass" | "solid";
};

export function BentoCard({
  title,
  description,
  icon,
  colSpan = "md:col-span-6",
  rowSpan,
  variant = "glass",
  className,
  children,
  ...props
}: BentoCardProps) {
  return (
    <GlowCard
      className={cn(
        "group relative overflow-hidden",
        variant === "glass" ? "bg-[hsl(var(--card))]/40 backdrop-blur-md" : "bg-[hsl(var(--card))]/70 backdrop-blur",
        colSpan,
        rowSpan,
        className
      )}
      {...props}
    >
      <div className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
        <div className="absolute inset-0 bg-[radial-gradient(800px_circle_at_30%_0%,hsl(var(--foreground)/0.10),transparent_60%),radial-gradient(900px_circle_at_80%_30%,hsl(var(--foreground)/0.08),transparent_62%)]" />
      </div>
      <div className="relative flex h-full flex-col p-5">
        <div className="flex items-start gap-3">
          {icon ? (
            <div className="mt-0.5 inline-flex h-9 w-9 items-center justify-center rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))]/60 text-[hsl(var(--foreground))] shadow-sm">
              {icon}
            </div>
          ) : null}
          <div className="min-w-0">
            <div className="text-sm font-semibold tracking-tight">{title}</div>
            {description ? <div className="mt-1 text-sm text-[hsl(var(--foreground))/0.65]">{description}</div> : null}
          </div>
        </div>
        {children ? <div className="mt-4 flex-1">{children}</div> : null}
      </div>
    </GlowCard>
  );
}
`,
  "components/magic/scroll-reveal.tsx": `"use client";
import * as React from "react";
import { motion, type MotionProps } from "framer-motion";
import { cn } from "@/lib/utils";

type Props = MotionProps & {
  className?: string;
  as?: "div" | "section" | "header" | "footer" | "main" | "article";
  children?: React.ReactNode;
  delay?: number;
};

export function ScrollReveal({ className, as = "div", children, delay = 0, ...props }: Props) {
  const Comp = motion[as] as unknown as React.ComponentType<MotionProps & { className?: string; children?: React.ReactNode }>;
  return (
    <Comp
      initial={{ opacity: 0, y: 14, filter: "blur(6px)" }}
      whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
      viewport={{ once: true, margin: "-20% 0px -20% 0px" }}
      transition={{ duration: 0.6, delay, ease: [0.21, 0.9, 0.2, 1] }}
      className={cn(className)}
      {...props}
    >
      {children}
    </Comp>
  );
}
`,
};

export function buildNextLandingBundle({
  productionPageTsx,
}: BundleInput): VercelFile[] {
  const generated = sanitizeProductionPageTsx(productionPageTsx);

  const wrapperPage = `import GeneratedPage from "./generated-page";
import { ContactForm } from "@/components/contact-form";

export default function Page() {
  const clientId = process.env.NEXT_PUBLIC_LEADS_CLIENT_ID;
  return (
    <>
      <GeneratedPage />
      <ContactForm clientId={clientId} />
    </>
  );
}
`;

  const files: VercelFile[] = [
    {
      file: "package.json",
      data: JSON.stringify(PACKAGE_JSON, null, 2),
      encoding: "utf-8",
    },
    { file: "vercel.json", data: VERCEL_JSON, encoding: "utf-8" },
    { file: "next.config.ts", data: NEXT_CONFIG_TS, encoding: "utf-8" },
    { file: "postcss.config.mjs", data: POSTCSS_CONFIG_MJS, encoding: "utf-8" },
    {
      file: "tsconfig.json",
      data: JSON.stringify(TSCONFIG_JSON, null, 2),
      encoding: "utf-8",
    },
    { file: "next-env.d.ts", data: NEXT_ENV_D_TS, encoding: "utf-8" },
    { file: "app/globals.css", data: GLOBALS_CSS, encoding: "utf-8" },
    { file: "app/layout.tsx", data: ROOT_LAYOUT_TSX, encoding: "utf-8" },
    { file: "app/generated-page.tsx", data: generated, encoding: "utf-8" },
    { file: "app/page.tsx", data: wrapperPage, encoding: "utf-8" },
    { file: "lib/utils.ts", data: LIB_UTILS_TS, encoding: "utf-8" },
    { file: "lib/firebase/client.ts", data: FIREBASE_CLIENT_TS, encoding: "utf-8" },
    { file: "lib/firebase/leads.ts", data: FIREBASE_LEADS_TS, encoding: "utf-8" },
    { file: "components/contact-form.tsx", data: CONTACT_FORM_TSX, encoding: "utf-8" },
  ];

  for (const [path, data] of Object.entries(MAGIC_COMPONENTS)) {
    files.push({ file: path, data, encoding: "utf-8" });
  }

  return files;
}

